=== Tiagoferrao6/L2Journey/dist/game/data/xsd/zones.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="list">
		<xs:complexType>
			<xs:sequence minOccurs="1" maxOccurs="1">
				<xs:element name="zone" minOccurs="1" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence minOccurs="1" maxOccurs="1">
							<xs:element name="stat" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:attribute name="name" use="required">
										<xs:simpleType>
											<xs:restriction base="xs:token">
												<xs:enumeration value="affectedLvlMin" />
												<xs:enumeration value="affectedRace" />
												<xs:enumeration value="allowStore" />
												<xs:enumeration value="castleId" />
												<xs:enumeration value="chance" />
												<xs:enumeration value="clanHallId" />
												<xs:enumeration value="dmgHPSec" />
												<xs:enumeration value="default_enabled" />
												<xs:enumeration value="domainId" />
												<xs:enumeration value="enterMsgId" />
												<xs:enumeration value="eventId" />
												<xs:enumeration value="fortId" />
												<xs:enumeration value="HpRegenBonus" />
												<xs:enumeration value="initialDelay" />
												<xs:enumeration value="instanceId" />
												<xs:enumeration value="InvadeTime" />
												<xs:enumeration value="leaveMsgId" />
												<xs:enumeration value="maxDynamicSkillCount" />
												<xs:enumeration value="move_bonus" />
												<xs:enumeration value="MpRegenBonus" />
												<xs:enumeration value="NoBookmark" />
												<xs:enumeration value="NoItemDrop" />
												<xs:enumeration value="oustX" />
												<xs:enumeration value="oustY" />
												<xs:enumeration value="oustZ" />
												<xs:enumeration value="residenceId" />
												<xs:enumeration value="residenceZoneId" />
												<xs:enumeration value="restartAllowedTime" />
												<xs:enumeration value="restartTime" />
												<xs:enumeration value="reuse" />
												<xs:enumeration value="removeEffectsOnExit" />
												<xs:enumeration value="showDangerIcon" />
												<xs:enumeration value="skillIdLvl" />
												<xs:enumeration value="spawnMaxX" />
												<xs:enumeration value="spawnMaxY" />
												<xs:enumeration value="spawnMaxZ" />
												<xs:enumeration value="spawnMinX" />
												<xs:enumeration value="spawnMinY" />
												<xs:enumeration value="spawnMinZ" />
												<xs:enumeration value="spawnZ" />
												<xs:enumeration value="targetClass" />
												<xs:enumeration value="taxById" />
												<xs:enumeration value="territoryId" />
												<xs:enumeration value="townId" />
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
									<xs:attribute name="val" type="xs:token" use="required" />
								</xs:complexType>
							</xs:element>
							<xs:element name="node" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:attribute name="X" type="xs:integer" use="required" />
									<xs:attribute name="Y" type="xs:integer" use="required" />
								</xs:complexType>
							</xs:element>
							<xs:element name="race" maxOccurs="unbounded" minOccurs="0">
								<xs:complexType>
									<xs:attribute name="point" type="xs:token" use="required" />
									<xs:attribute name="name" type="xs:token" use="required" />
								</xs:complexType>
							</xs:element>
							<xs:element name="spawn" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:attribute name="type">
										<xs:simpleType>
											<xs:restriction base="xs:token">
												<xs:enumeration value="banish" />
												<xs:enumeration value="blueBanishPoint" />
												<xs:enumeration value="blueStartPoint" />
												<xs:enumeration value="challenger" />
												<xs:enumeration value="chaotic" />
												<xs:enumeration value="entrance" />
												<xs:enumeration value="other" />
												<xs:enumeration value="redBanishPoint" />
												<xs:enumeration value="redStartPoint" />
												<xs:enumeration value="spectatorSpawn" />
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
									<xs:attribute name="X" type="xs:integer" use="required" />
									<xs:attribute name="Y" type="xs:integer" use="required" />
									<xs:attribute name="Z" type="xs:integer" use="required" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="id" type="xs:positiveInteger" />
						<xs:attribute name="maxZ" type="xs:integer" use="required" />
						<xs:attribute name="minZ" type="xs:integer" use="required" />
						<xs:attribute name="name" type="xs:normalizedString" use="required" />
						<xs:attribute name="rad" type="xs:positiveInteger" />
						<xs:attribute name="shape" use="required">
							<xs:simpleType>
								<xs:restriction base="xs:token">
									<xs:enumeration value="Cuboid" />
									<xs:enumeration value="Cylinder" />
									<xs:enumeration value="NPoly" />
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
						<xs:attribute name="type" use="required">
							<xs:simpleType>
								<xs:restriction base="xs:token">
									<xs:enumeration value="ArenaZone" />
									<xs:enumeration value="BossZone" />
									<xs:enumeration value="CastleZone" />
									<xs:enumeration value="ClanHallZone" />
									<xs:enumeration value="CleftZone" />
									<xs:enumeration value="ConditionZone" />
									<xs:enumeration value="DamageZone" />
									<xs:enumeration value="DerbyTrackZone" />
									<xs:enumeration value="EffectZone" />
									<xs:enumeration value="FishingZone" />
									<xs:enumeration value="FortZone" />
									<xs:enumeration value="HotSpringGreenSpa" />
									<xs:enumeration value="HotSpringRedSpa" />
									<xs:enumeration value="HotSpringYellowSpa" />
									<xs:enumeration value="HqZone" />
									<xs:enumeration value="JailZone" />
									<xs:enumeration value="LandingZone" />
									<xs:enumeration value="MotherTreeZone" />
									<xs:enumeration value="NoDropItemZone" />
									<xs:enumeration value="NoLandingZone" />
									<xs:enumeration value="NoRestartZone" />
									<xs:enumeration value="NoStoreZone" />
									<xs:enumeration value="NoSummonFriendZone" />
									<xs:enumeration value="NoPvPZone" />
									<xs:enumeration value="NpcSpawnTerritory" />
									<xs:enumeration value="MultiFloorZone" />
									<xs:enumeration value="OlympiadStadiumZone" />
									<xs:enumeration value="PeaceZone" />
									<xs:enumeration value="ResidenceHallTeleportZone" />
									<xs:enumeration value="ResidenceTeleportZone" />
									<xs:enumeration value="RespawnZone" />
									<xs:enumeration value="ScriptZone" />
									<xs:enumeration value="SiegableHallZone" />
									<xs:enumeration value="SiegeZone" />
									<xs:enumeration value="SwampZone" />
									<xs:enumeration value="TaxZone" />
									<xs:enumeration value="TerritoryWarZone" />
									<xs:enumeration value="TownZone" />
									<xs:enumeration value="WaterZone" />
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="enabled" type="xs:boolean" use="required" />
		</xs:complexType>
	</xs:element>
</xs:schema>

=== Tiagoferrao6/L2Journey/dist/game/data/zones/water.xml
<?xml version="1.0" encoding="UTF-8"?>
<list enabled="true" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/zones.xsd">
	<!-- Water Zones -->
	<zone name="11_23_water1" type="WaterZone" shape="Cuboid" minZ="-4779" maxZ="-3779">
		<node X="-294912" Y="163839" />
		<node X="-262144" Y="196607" />
	</zone>
	<zone name="11_24_water1" type="WaterZone" shape="Cuboid" minZ="-4779" maxZ="-3779">
		<node X="-294912" Y="196607" />
		<node X="-262144" Y="229375" />
	</zone>
	<zone name="11_25_water1" type="WaterZone" shape="Cuboid" minZ="-4779" maxZ="-3779">
		<node X="-294912" Y="229375" />
		<node X="-262144" Y="262143" />
	</zone>
	<zone name="11_26_water1" type="WaterZone" shape="Cuboid" minZ="-4779" maxZ="-3779">
		<node X="-294912" Y="262144" />
		<node X="-262144" Y="294912" />
	</zone>
	<zone name="12_23_water1" type="WaterZone" shape="Cuboid" minZ="-4779" maxZ="-3779">
		<node X="-262144" Y="163839" />
		<node X="-229376" Y="196607" />
	</zone>
	<zone name="12_24_water1" type="WaterZone" shape="Cuboid" minZ="-4779" maxZ="-3779">
		<node X="-262144" Y="196607" />
		<node X="-229376" Y="229375" />
	</zone>
	<zone name="12_25_water1" type="WaterZone" shape="Cuboid" minZ="-4779" maxZ="-3779">
		<node X="-262144" Y="229375" />
		<node X="-229376" Y="262143" />
	</zone>
	<zone name="12_26_water1" type="WaterZone" shape="Cuboid" minZ="-4779" maxZ="-3779">
		<node X="-262144" Y="262144" />
		<node X="-229376" Y="294912" />
	</zone>
	<zone name="13_23_water1" type="WaterZone" shape="Cuboid" minZ="-4779" maxZ="-3779">
		<node X="-229376" Y="163839" />
		<node X="-196608" Y="196607" />
	</zone>
	<zone name="13_24_water1" type="WaterZone" shape="Cuboid" minZ="-4779" maxZ="-3779">
		<node X="-229376" Y="223231" />
		<node X="-196608" Y="229375" />
	</zone>
	<zone name="13_24_water2" type="WaterZone" shape="Cuboid" minZ="-4779" maxZ="-3779">
		<node X="-229376" Y="200447" />
		<node X="-225024" Y="223231" />
	</zone>
	<zone name="13_24_water3" type="WaterZone" shape="Cuboid" minZ="-4779" maxZ="-3779">
		<node X="-229376" Y="196607" />
		<node X="-196608" Y="200447" />
	</zone>
	<zone name="13_24_water4" type="WaterZone" shape="Cuboid" minZ="-4779" maxZ="-3779">
		<node X="-206336" Y="200447" />
		<node X="-196608" Y="204287" />
	</zone>
	<zone name="13_24_water5" type="WaterZone" shape="Cuboid" minZ="-4779" maxZ="-3779">
		<node X="-225024" Y="200447" />
		<node X="-217344" Y="207871" />
	</zone>
	<zone name="13_24_water6" type="WaterZone" shape="Cuboid" minZ="-4779" maxZ="-3779">
		<node X="-219648" Y="215039" />
		<node X="-213248" Y="223231" />
	</zone>
	<zone name="13_25_water1" type="WaterZone" shape="Cuboid" minZ="-4779" maxZ="-3779">
		<node X="-229376" Y="229375" />
		<node X="-196608" Y="262143" />
	</zone>
	<zone name="13_26_water1" type="WaterZone" shape="Cuboid" minZ="-4779" maxZ="-3779">
		<node X="-229376" Y="262144" />
		<node X="-196608" Y="294912" />
	</zone>
	<zone name="14_23_water1" type="WaterZone" shape="Cuboid" minZ="-4779" maxZ="-3779">
		<node X="-196608" Y="163839" />
		<node X="-163840" Y="196607" />
	</zone>
	<zone name="14_24_water1" type="WaterZone" shape="Cuboid" minZ="-4779" maxZ="-3779">
		<node X="-193152" Y="196607" />
		<node X="-168960" Y="202239" />
	</zone>
	<zone name="14_24_water2" type="WaterZone" shape="Cuboid" minZ="-4779" maxZ="-3779">
		<node X="-168960" Y="196607" />
		<node X="-163840" Y="229375" />
	</zone>
	<zone name="14_24_water3" type="WaterZone" shape="Cuboid" minZ="-4779" maxZ="-3779">
		<node X="-196608" Y="222975" />
		<node X="-179584" Y="229375" />
	</zone>
	<zone name="14_24_water4" type="WaterZone" shape="Cuboid" minZ="-4779" maxZ="-3779">
		<node X="-179584" Y="224767" />
		<node X="-168960" Y="229375" />
	</zone>
	<zone name="14_24_water5" type="WaterZone" shape="Cuboid" minZ="-4779" maxZ="-3779">
		<node X="-186880" Y="218111" />
		<node X="-179584" Y="222975" />
	</zone>
	<zone name="14_24_water6" type="WaterZone" shape="Cuboid" minZ="-4779" maxZ="-3779">
		<node X="-196608" Y="196607" />
		<node X="-193152" Y="203775" />
	</zone>
	<zone name="14_25_water1" type="WaterZone" shape="Cuboid" minZ="-4779" maxZ="-3779">
		<node X="-196608" Y="229375" />
		<node X="-163840" Y="262143" />
	</zone>
	<zone name="14_25_water2" type="WaterZone" shape="Cuboid" minZ="-2192" maxZ="-144">
		<node X="-187152" Y="240401" />
		<node X="-183376" Y="245393" />
	</zone>
	<zone name="14_25_water3" type="WaterZone" shape="Cuboid" minZ="-2192" maxZ="-144">
		<node X="-183376" Y="241768" />
		<node X="-182032" Y="244872" />
	</zone>
	<zone name="14_25_water4" type="WaterZone" shape="Cuboid" minZ="-2192" maxZ="-144">
		<node X="-183376" Y="240968" />
		<node X="-182799" Y="241768" />
	</zone>
	<zone name="14_26_water1" type="WaterZone" shape="Cuboid" minZ="-4779" maxZ="-3779">
		<node X="-196608" Y="262144" />
		<node X="-163840" Y="294912" />
	</zone>
	<zone name="15_23_water1" type="WaterZone" shape="Cuboid" minZ="-4784" maxZ="-3784">
		<node X="-163840" Y="163839" />
		<node X="-131072" Y="196607" />
	</zone>
	<zone name="15_24_water1" type="WaterZone" shape="Cuboid" minZ="-4779" maxZ="-3779">
		<node X="-163840" Y="196608" />
		<node X="-131072" Y="229376" />
	</zone>
	<zone name="15_25_water1" type="WaterZone" shape="Cuboid" minZ="-4779" maxZ="-3779">
		<node X="-163840" Y="229375" />
		<node X="-131072" Y="262143" />
	</zone>
	<zone name="15_26_water1" type="WaterZone" shape="Cuboid" minZ="-4783" maxZ="-3783">
		<node X="-163840" Y="262144" />
		<node X="-131072" Y="294912" />
	</zone>
	<zone name="16_11_water1" type="WaterZone" shape="Cuboid" minZ="-4780" maxZ="-3780">
		<node X="-131072" Y="-229376" />
		<node X="-98304" Y="-196608" />
	</zone>
	<zone name="16_14_water1" type="WaterZone" shape="Cuboid" minZ="-4780" maxZ="-3780">
		<node X="-131072" Y="-131072" />
		<node X="-98304" Y="-98304" />
	</zone>
	<zone name="16_15_water1" type="WaterZone" shape="Cuboid" minZ="-4780" maxZ="-3780">
		<node X="-131072" Y="-98304" />
		<node X="-98304" Y="-65536" />
	</zone>
	<zone name="16_16_water1" type="WaterZone" shape="Cuboid" minZ="-4780" maxZ="-3780">
		<node X="-131072" Y="-65536" />
		<node X="-98304" Y="-32768" />
	</zone>
	<zone name="16_17_water1" type="WaterZone" shape="Cuboid" minZ="-4780" maxZ="-3780">
		<node X="-131072" Y="-32768" />
		<node X="-98304" Y="0" />
	</zone>
	<zone name="16_18_water1" type="WaterZone" shape="Cuboid" minZ="-4780" maxZ="-3780">
		<node X="-131072" Y="0" />
		<node X="-98304" Y="32768" />
	</zone>
	<zone name="16_19_water1" type="WaterZone" shape="Cuboid" minZ="-2431" maxZ="-1643">
		<node X="-119580" Y="51908" />
		<node X="-116148" Y="55660" />
	</zone>
	<zone name="16_19_water2" type="WaterZone" shape="Cuboid" minZ="237" maxZ="337">
		<node X="-118668" Y="45364" />
		<node X="-117492" Y="46588" />
	</zone>
	<zone name="16_19_water3" type="WaterZone" shape="Cuboid" minZ="237" maxZ="337">
		<node X="-117492" Y="45572" />
		<node X="-117020" Y="46332" />
	</zone>
	<zone name="16_19_water4" type="WaterZone" shape="Cuboid" minZ="237" maxZ="337">
		<node X="-119140" Y="45572" />
		<node X="-118668" Y="46332" />
	</zone>
	<zone name="16_19_water5" type="WaterZone" shape="Cuboid" minZ="-4779" maxZ="-3779">
		<node X="-131072" Y="32768" />
		<node X="-125120" Y="65536" />
	</zone>
	<zone name="16_19_water6" type="WaterZone" shape="Cuboid" minZ="-4779" maxZ="-3779">
		<node X="-125120" Y="32768" />
		<node X="-98304" Y="38848" />
	</zone>
	<zone name="16_19_water7" type="WaterZone" shape="Cuboid" minZ="-4779" maxZ="-3779">
		<node X="-102528" Y="60608" />
		<node X="-98304" Y="65536" />
	</zone>
	<zone name="16_20_water1" type="WaterZone" shape="Cuboid" minZ="-4780" maxZ="-3780">
		<node X="-131072" Y="65536" />
		<node X="-98304" Y="98304" />
	</zone>
	<zone name="16_20_water2" type="WaterZone" shape="Cuboid" minZ="-12729" maxZ="-12721">
		<node X="-117708" Y="86820" />
		<node X="-116988" Y="87540" />
	</zone>
	<zone name="16_20_water3" type="WaterZone" shape="Cuboid" minZ="-12822" maxZ="-12814">
		<node X="-115811" Y="86821" />
		<node X="-115091" Y="87541" />
	</zone>
	<zone name="16_20_water4" type="WaterZone" shape="Cuboid" minZ="-12919" maxZ="-12911">
		<node X="-113915" Y="86823" />
		<node X="-113195" Y="87543" />
	</zone>
	<zone name="16_20_water5" type="WaterZone" shape="Cuboid" minZ="-12632" maxZ="-12624">
		<node X="-119992" Y="86728" />
		<node X="-119096" Y="87624" />
	</zone>
	<zone name="16_20_water6" type="WaterZone" shape="Cuboid" minZ="-12632" maxZ="-12624">
		<node X="-119096" Y="86960" />
		<node X="-118880" Y="87392" />
	</zone>
	<zone name="16_20_water7" type="WaterZone" shape="Cuboid" minZ="-12632" maxZ="-12624">
		<node X="-120224" Y="86960" />
		<node X="-119992" Y="87392" />
	</zone>
	<zone name="16_20_water8" type="WaterZone" shape="Cuboid" minZ="-12632" maxZ="-12624">
		<node X="-119760" Y="86520" />
		<node X="-119328" Y="86728" />
	</zone>
	<zone name="16_20_water9" type="WaterZone" shape="Cuboid" minZ="-12632" maxZ="-12624">
		<node X="-119760" Y="87624" />
		<node X="-119328" Y="87848" />
	</zone>
	<zone name="16_21_water1" type="WaterZone" shape="Cuboid" minZ="-4780" maxZ="-3780">
		<node X="-131071" Y="98303" />
		<node X="-98303" Y="131071" />
	</zone>
	<zone name="16_22_water1" type="WaterZone" shape="Cuboid" minZ="-4780" maxZ="-3780">
		<node X="-131071" Y="131072" />
		<node X="-98303" Y="163840" />
	</zone>
	<zone name="16_23_water1" type="WaterZone" shape="Cuboid" minZ="-4780" maxZ="-3780">
		<node X="-131071" Y="163840" />
		<node X="-98303" Y="196608" />
	</zone>
	<zone name="16_24_water1" type="WaterZone" shape="Cuboid" minZ="-7779" maxZ="-3779">
		<node X="-131072" Y="196607" />
		<node X="-98304" Y="229375" />
	</zone>
